# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SERVER distribute

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: AlmaLinux-release-9.2

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/deva/my-next-app
            sudo /usr/local/bin/pm2 stop 0
            sudo git fetch --all
            sudo git reset --hard
            sudo git pull
            sudo /usr/local/bin/pnpm update
            sudo /usr/local/bin/pnpm build
            sudo /usr/local/bin/pm2 restart 0 --update-env
